<?php
/**
 * CfdiReceptor
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Facter\Sdk\Model;

use \ArrayAccess;
use \Facter\Sdk\ObjectSerializer;

/**
 * CfdiReceptor Class Doc Comment
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CfdiReceptor implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CfdiReceptor';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rfc' => 'string',
        'nombre' => 'string',
        'domicilio_fiscal_receptor' => 'string',
        'regimen_fiscal_receptor' => 'string',
        'uso_cfdi' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rfc' => null,
        'nombre' => null,
        'domicilio_fiscal_receptor' => null,
        'regimen_fiscal_receptor' => null,
        'uso_cfdi' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rfc' => false,
        'nombre' => false,
        'domicilio_fiscal_receptor' => false,
        'regimen_fiscal_receptor' => false,
        'uso_cfdi' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rfc' => 'Rfc',
        'nombre' => 'Nombre',
        'domicilio_fiscal_receptor' => 'DomicilioFiscalReceptor',
        'regimen_fiscal_receptor' => 'RegimenFiscalReceptor',
        'uso_cfdi' => 'UsoCFDI'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rfc' => 'setRfc',
        'nombre' => 'setNombre',
        'domicilio_fiscal_receptor' => 'setDomicilioFiscalReceptor',
        'regimen_fiscal_receptor' => 'setRegimenFiscalReceptor',
        'uso_cfdi' => 'setUsoCfdi'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rfc' => 'getRfc',
        'nombre' => 'getNombre',
        'domicilio_fiscal_receptor' => 'getDomicilioFiscalReceptor',
        'regimen_fiscal_receptor' => 'getRegimenFiscalReceptor',
        'uso_cfdi' => 'getUsoCfdi'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rfc', $data ?? [], null);
        $this->setIfExists('nombre', $data ?? [], null);
        $this->setIfExists('domicilio_fiscal_receptor', $data ?? [], null);
        $this->setIfExists('regimen_fiscal_receptor', $data ?? [], null);
        $this->setIfExists('uso_cfdi', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['rfc'] === null) {
            $invalidProperties[] = "'rfc' can't be null";
        }
        if ($this->container['nombre'] === null) {
            $invalidProperties[] = "'nombre' can't be null";
        }
        if ($this->container['domicilio_fiscal_receptor'] === null) {
            $invalidProperties[] = "'domicilio_fiscal_receptor' can't be null";
        }
        if ($this->container['regimen_fiscal_receptor'] === null) {
            $invalidProperties[] = "'regimen_fiscal_receptor' can't be null";
        }
        if ($this->container['uso_cfdi'] === null) {
            $invalidProperties[] = "'uso_cfdi' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rfc
     *
     * @return string
     */
    public function getRfc()
    {
        return $this->container['rfc'];
    }

    /**
     * Sets rfc
     *
     * @param string $rfc rfc
     *
     * @return self
     */
    public function setRfc($rfc)
    {
        if (is_null($rfc)) {
            throw new \InvalidArgumentException('non-nullable rfc cannot be null');
        }
        $this->container['rfc'] = $rfc;

        return $this;
    }

    /**
     * Gets nombre
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->container['nombre'];
    }

    /**
     * Sets nombre
     *
     * @param string $nombre nombre
     *
     * @return self
     */
    public function setNombre($nombre)
    {
        if (is_null($nombre)) {
            throw new \InvalidArgumentException('non-nullable nombre cannot be null');
        }
        $this->container['nombre'] = $nombre;

        return $this;
    }

    /**
     * Gets domicilio_fiscal_receptor
     *
     * @return string
     */
    public function getDomicilioFiscalReceptor()
    {
        return $this->container['domicilio_fiscal_receptor'];
    }

    /**
     * Sets domicilio_fiscal_receptor
     *
     * @param string $domicilio_fiscal_receptor CP del receptor.
     *
     * @return self
     */
    public function setDomicilioFiscalReceptor($domicilio_fiscal_receptor)
    {
        if (is_null($domicilio_fiscal_receptor)) {
            throw new \InvalidArgumentException('non-nullable domicilio_fiscal_receptor cannot be null');
        }
        $this->container['domicilio_fiscal_receptor'] = $domicilio_fiscal_receptor;

        return $this;
    }

    /**
     * Gets regimen_fiscal_receptor
     *
     * @return string
     */
    public function getRegimenFiscalReceptor()
    {
        return $this->container['regimen_fiscal_receptor'];
    }

    /**
     * Sets regimen_fiscal_receptor
     *
     * @param string $regimen_fiscal_receptor regimen_fiscal_receptor
     *
     * @return self
     */
    public function setRegimenFiscalReceptor($regimen_fiscal_receptor)
    {
        if (is_null($regimen_fiscal_receptor)) {
            throw new \InvalidArgumentException('non-nullable regimen_fiscal_receptor cannot be null');
        }
        $this->container['regimen_fiscal_receptor'] = $regimen_fiscal_receptor;

        return $this;
    }

    /**
     * Gets uso_cfdi
     *
     * @return string
     */
    public function getUsoCfdi()
    {
        return $this->container['uso_cfdi'];
    }

    /**
     * Sets uso_cfdi
     *
     * @param string $uso_cfdi Catálogo c_UsoCFDI.
     *
     * @return self
     */
    public function setUsoCfdi($uso_cfdi)
    {
        if (is_null($uso_cfdi)) {
            throw new \InvalidArgumentException('non-nullable uso_cfdi cannot be null');
        }
        $this->container['uso_cfdi'] = $uso_cfdi;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


