<?php
/**
 * CfdiSummary
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Facter\Sdk\Model;

use \ArrayAccess;
use \Facter\Sdk\ObjectSerializer;

/**
 * CfdiSummary Class Doc Comment
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CfdiSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CfdiSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uuid' => 'string',
        'external_ref' => 'string',
        'emisor_rfc' => 'string',
        'receptor_rfc' => 'string',
        'serie' => 'string',
        'folio' => 'string',
        'total' => 'string',
        'moneda' => 'string',
        'tipo_de_comprobante' => 'string',
        'fecha_emision' => 'string',
        'fecha_timbrado' => 'string',
        'status' => 'string',
        'origin' => 'string',
        'links' => '\Facter\Sdk\Model\CfdiLinks'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'uuid' => 'uuid',
        'external_ref' => null,
        'emisor_rfc' => null,
        'receptor_rfc' => null,
        'serie' => null,
        'folio' => null,
        'total' => null,
        'moneda' => null,
        'tipo_de_comprobante' => null,
        'fecha_emision' => null,
        'fecha_timbrado' => null,
        'status' => null,
        'origin' => null,
        'links' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'uuid' => false,
        'external_ref' => true,
        'emisor_rfc' => false,
        'receptor_rfc' => false,
        'serie' => true,
        'folio' => true,
        'total' => false,
        'moneda' => false,
        'tipo_de_comprobante' => false,
        'fecha_emision' => false,
        'fecha_timbrado' => false,
        'status' => false,
        'origin' => false,
        'links' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'external_ref' => 'external_ref',
        'emisor_rfc' => 'emisor_rfc',
        'receptor_rfc' => 'receptor_rfc',
        'serie' => 'serie',
        'folio' => 'folio',
        'total' => 'total',
        'moneda' => 'moneda',
        'tipo_de_comprobante' => 'tipo_de_comprobante',
        'fecha_emision' => 'fecha_emision',
        'fecha_timbrado' => 'fecha_timbrado',
        'status' => 'status',
        'origin' => 'origin',
        'links' => 'links'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'external_ref' => 'setExternalRef',
        'emisor_rfc' => 'setEmisorRfc',
        'receptor_rfc' => 'setReceptorRfc',
        'serie' => 'setSerie',
        'folio' => 'setFolio',
        'total' => 'setTotal',
        'moneda' => 'setMoneda',
        'tipo_de_comprobante' => 'setTipoDeComprobante',
        'fecha_emision' => 'setFechaEmision',
        'fecha_timbrado' => 'setFechaTimbrado',
        'status' => 'setStatus',
        'origin' => 'setOrigin',
        'links' => 'setLinks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'external_ref' => 'getExternalRef',
        'emisor_rfc' => 'getEmisorRfc',
        'receptor_rfc' => 'getReceptorRfc',
        'serie' => 'getSerie',
        'folio' => 'getFolio',
        'total' => 'getTotal',
        'moneda' => 'getMoneda',
        'tipo_de_comprobante' => 'getTipoDeComprobante',
        'fecha_emision' => 'getFechaEmision',
        'fecha_timbrado' => 'getFechaTimbrado',
        'status' => 'getStatus',
        'origin' => 'getOrigin',
        'links' => 'getLinks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TIPO_DE_COMPROBANTE_I = 'I';
    public const TIPO_DE_COMPROBANTE_E = 'E';
    public const TIPO_DE_COMPROBANTE_P = 'P';
    public const TIPO_DE_COMPROBANTE_N = 'N';
    public const STATUS_VIGENTE = 'vigente';
    public const STATUS_CANCELADO = 'cancelado';
    public const STATUS_EN_PROCESO_CANCELACION = 'en_proceso_cancelacion';
    public const ORIGIN_API = 'API';
    public const ORIGIN_UI = 'UI';
    public const ORIGIN_EXTERNAL = 'EXTERNAL';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTipoDeComprobanteAllowableValues()
    {
        return [
            self::TIPO_DE_COMPROBANTE_I,
            self::TIPO_DE_COMPROBANTE_E,
            self::TIPO_DE_COMPROBANTE_P,
            self::TIPO_DE_COMPROBANTE_N,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_VIGENTE,
            self::STATUS_CANCELADO,
            self::STATUS_EN_PROCESO_CANCELACION,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOriginAllowableValues()
    {
        return [
            self::ORIGIN_API,
            self::ORIGIN_UI,
            self::ORIGIN_EXTERNAL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('external_ref', $data ?? [], null);
        $this->setIfExists('emisor_rfc', $data ?? [], null);
        $this->setIfExists('receptor_rfc', $data ?? [], null);
        $this->setIfExists('serie', $data ?? [], null);
        $this->setIfExists('folio', $data ?? [], null);
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('moneda', $data ?? [], null);
        $this->setIfExists('tipo_de_comprobante', $data ?? [], null);
        $this->setIfExists('fecha_emision', $data ?? [], null);
        $this->setIfExists('fecha_timbrado', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('origin', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getTipoDeComprobanteAllowableValues();
        if (!is_null($this->container['tipo_de_comprobante']) && !in_array($this->container['tipo_de_comprobante'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tipo_de_comprobante', must be one of '%s'",
                $this->container['tipo_de_comprobante'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getOriginAllowableValues();
        if (!is_null($this->container['origin']) && !in_array($this->container['origin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'origin', must be one of '%s'",
                $this->container['origin'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid uuid
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets external_ref
     *
     * @return string|null
     */
    public function getExternalRef()
    {
        return $this->container['external_ref'];
    }

    /**
     * Sets external_ref
     *
     * @param string|null $external_ref external_ref
     *
     * @return self
     */
    public function setExternalRef($external_ref)
    {
        if (is_null($external_ref)) {
            array_push($this->openAPINullablesSetToNull, 'external_ref');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_ref', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_ref'] = $external_ref;

        return $this;
    }

    /**
     * Gets emisor_rfc
     *
     * @return string|null
     */
    public function getEmisorRfc()
    {
        return $this->container['emisor_rfc'];
    }

    /**
     * Sets emisor_rfc
     *
     * @param string|null $emisor_rfc emisor_rfc
     *
     * @return self
     */
    public function setEmisorRfc($emisor_rfc)
    {
        if (is_null($emisor_rfc)) {
            throw new \InvalidArgumentException('non-nullable emisor_rfc cannot be null');
        }
        $this->container['emisor_rfc'] = $emisor_rfc;

        return $this;
    }

    /**
     * Gets receptor_rfc
     *
     * @return string|null
     */
    public function getReceptorRfc()
    {
        return $this->container['receptor_rfc'];
    }

    /**
     * Sets receptor_rfc
     *
     * @param string|null $receptor_rfc receptor_rfc
     *
     * @return self
     */
    public function setReceptorRfc($receptor_rfc)
    {
        if (is_null($receptor_rfc)) {
            throw new \InvalidArgumentException('non-nullable receptor_rfc cannot be null');
        }
        $this->container['receptor_rfc'] = $receptor_rfc;

        return $this;
    }

    /**
     * Gets serie
     *
     * @return string|null
     */
    public function getSerie()
    {
        return $this->container['serie'];
    }

    /**
     * Sets serie
     *
     * @param string|null $serie serie
     *
     * @return self
     */
    public function setSerie($serie)
    {
        if (is_null($serie)) {
            array_push($this->openAPINullablesSetToNull, 'serie');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('serie', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['serie'] = $serie;

        return $this;
    }

    /**
     * Gets folio
     *
     * @return string|null
     */
    public function getFolio()
    {
        return $this->container['folio'];
    }

    /**
     * Sets folio
     *
     * @param string|null $folio folio
     *
     * @return self
     */
    public function setFolio($folio)
    {
        if (is_null($folio)) {
            array_push($this->openAPINullablesSetToNull, 'folio');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('folio', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['folio'] = $folio;

        return $this;
    }

    /**
     * Gets total
     *
     * @return string|null
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param string|null $total total
     *
     * @return self
     */
    public function setTotal($total)
    {
        if (is_null($total)) {
            throw new \InvalidArgumentException('non-nullable total cannot be null');
        }
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets moneda
     *
     * @return string|null
     */
    public function getMoneda()
    {
        return $this->container['moneda'];
    }

    /**
     * Sets moneda
     *
     * @param string|null $moneda moneda
     *
     * @return self
     */
    public function setMoneda($moneda)
    {
        if (is_null($moneda)) {
            throw new \InvalidArgumentException('non-nullable moneda cannot be null');
        }
        $this->container['moneda'] = $moneda;

        return $this;
    }

    /**
     * Gets tipo_de_comprobante
     *
     * @return string|null
     */
    public function getTipoDeComprobante()
    {
        return $this->container['tipo_de_comprobante'];
    }

    /**
     * Sets tipo_de_comprobante
     *
     * @param string|null $tipo_de_comprobante tipo_de_comprobante
     *
     * @return self
     */
    public function setTipoDeComprobante($tipo_de_comprobante)
    {
        if (is_null($tipo_de_comprobante)) {
            throw new \InvalidArgumentException('non-nullable tipo_de_comprobante cannot be null');
        }
        $allowedValues = $this->getTipoDeComprobanteAllowableValues();
        if (!in_array($tipo_de_comprobante, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tipo_de_comprobante', must be one of '%s'",
                    $tipo_de_comprobante,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tipo_de_comprobante'] = $tipo_de_comprobante;

        return $this;
    }

    /**
     * Gets fecha_emision
     *
     * @return string|null
     */
    public function getFechaEmision()
    {
        return $this->container['fecha_emision'];
    }

    /**
     * Sets fecha_emision
     *
     * @param string|null $fecha_emision fecha_emision
     *
     * @return self
     */
    public function setFechaEmision($fecha_emision)
    {
        if (is_null($fecha_emision)) {
            throw new \InvalidArgumentException('non-nullable fecha_emision cannot be null');
        }
        $this->container['fecha_emision'] = $fecha_emision;

        return $this;
    }

    /**
     * Gets fecha_timbrado
     *
     * @return string|null
     */
    public function getFechaTimbrado()
    {
        return $this->container['fecha_timbrado'];
    }

    /**
     * Sets fecha_timbrado
     *
     * @param string|null $fecha_timbrado fecha_timbrado
     *
     * @return self
     */
    public function setFechaTimbrado($fecha_timbrado)
    {
        if (is_null($fecha_timbrado)) {
            throw new \InvalidArgumentException('non-nullable fecha_timbrado cannot be null');
        }
        $this->container['fecha_timbrado'] = $fecha_timbrado;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets origin
     *
     * @return string|null
     */
    public function getOrigin()
    {
        return $this->container['origin'];
    }

    /**
     * Sets origin
     *
     * @param string|null $origin origin
     *
     * @return self
     */
    public function setOrigin($origin)
    {
        if (is_null($origin)) {
            throw new \InvalidArgumentException('non-nullable origin cannot be null');
        }
        $allowedValues = $this->getOriginAllowableValues();
        if (!in_array($origin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'origin', must be one of '%s'",
                    $origin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['origin'] = $origin;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Facter\Sdk\Model\CfdiLinks|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Facter\Sdk\Model\CfdiLinks|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


