<?php
/**
 * Concepto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Facter\Sdk\Model;

use \ArrayAccess;
use \Facter\Sdk\ObjectSerializer;

/**
 * Concepto Class Doc Comment
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Concepto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Concepto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'clave_prod_serv' => 'string',
        'no_identificacion' => 'string',
        'cantidad' => 'string',
        'clave_unidad' => 'string',
        'unidad' => 'string',
        'descripcion' => 'string',
        'valor_unitario' => 'string',
        'importe' => 'string',
        'descuento' => 'string',
        'objeto_imp' => 'string',
        'impuestos' => '\Facter\Sdk\Model\ImpuestosConcepto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'clave_prod_serv' => null,
        'no_identificacion' => null,
        'cantidad' => null,
        'clave_unidad' => null,
        'unidad' => null,
        'descripcion' => null,
        'valor_unitario' => null,
        'importe' => null,
        'descuento' => null,
        'objeto_imp' => null,
        'impuestos' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'clave_prod_serv' => false,
        'no_identificacion' => true,
        'cantidad' => false,
        'clave_unidad' => false,
        'unidad' => true,
        'descripcion' => false,
        'valor_unitario' => false,
        'importe' => false,
        'descuento' => true,
        'objeto_imp' => false,
        'impuestos' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'clave_prod_serv' => 'ClaveProdServ',
        'no_identificacion' => 'NoIdentificacion',
        'cantidad' => 'Cantidad',
        'clave_unidad' => 'ClaveUnidad',
        'unidad' => 'Unidad',
        'descripcion' => 'Descripcion',
        'valor_unitario' => 'ValorUnitario',
        'importe' => 'Importe',
        'descuento' => 'Descuento',
        'objeto_imp' => 'ObjetoImp',
        'impuestos' => 'Impuestos'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'clave_prod_serv' => 'setClaveProdServ',
        'no_identificacion' => 'setNoIdentificacion',
        'cantidad' => 'setCantidad',
        'clave_unidad' => 'setClaveUnidad',
        'unidad' => 'setUnidad',
        'descripcion' => 'setDescripcion',
        'valor_unitario' => 'setValorUnitario',
        'importe' => 'setImporte',
        'descuento' => 'setDescuento',
        'objeto_imp' => 'setObjetoImp',
        'impuestos' => 'setImpuestos'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'clave_prod_serv' => 'getClaveProdServ',
        'no_identificacion' => 'getNoIdentificacion',
        'cantidad' => 'getCantidad',
        'clave_unidad' => 'getClaveUnidad',
        'unidad' => 'getUnidad',
        'descripcion' => 'getDescripcion',
        'valor_unitario' => 'getValorUnitario',
        'importe' => 'getImporte',
        'descuento' => 'getDescuento',
        'objeto_imp' => 'getObjetoImp',
        'impuestos' => 'getImpuestos'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const OBJETO_IMP__01 = '01';
    public const OBJETO_IMP__02 = '02';
    public const OBJETO_IMP__03 = '03';
    public const OBJETO_IMP__04 = '04';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getObjetoImpAllowableValues()
    {
        return [
            self::OBJETO_IMP__01,
            self::OBJETO_IMP__02,
            self::OBJETO_IMP__03,
            self::OBJETO_IMP__04,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('clave_prod_serv', $data ?? [], null);
        $this->setIfExists('no_identificacion', $data ?? [], null);
        $this->setIfExists('cantidad', $data ?? [], null);
        $this->setIfExists('clave_unidad', $data ?? [], null);
        $this->setIfExists('unidad', $data ?? [], null);
        $this->setIfExists('descripcion', $data ?? [], null);
        $this->setIfExists('valor_unitario', $data ?? [], null);
        $this->setIfExists('importe', $data ?? [], null);
        $this->setIfExists('descuento', $data ?? [], null);
        $this->setIfExists('objeto_imp', $data ?? [], null);
        $this->setIfExists('impuestos', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['clave_prod_serv'] === null) {
            $invalidProperties[] = "'clave_prod_serv' can't be null";
        }
        if ($this->container['cantidad'] === null) {
            $invalidProperties[] = "'cantidad' can't be null";
        }
        if ($this->container['clave_unidad'] === null) {
            $invalidProperties[] = "'clave_unidad' can't be null";
        }
        if ($this->container['descripcion'] === null) {
            $invalidProperties[] = "'descripcion' can't be null";
        }
        if ($this->container['valor_unitario'] === null) {
            $invalidProperties[] = "'valor_unitario' can't be null";
        }
        if ($this->container['importe'] === null) {
            $invalidProperties[] = "'importe' can't be null";
        }
        if ($this->container['objeto_imp'] === null) {
            $invalidProperties[] = "'objeto_imp' can't be null";
        }
        $allowedValues = $this->getObjetoImpAllowableValues();
        if (!is_null($this->container['objeto_imp']) && !in_array($this->container['objeto_imp'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'objeto_imp', must be one of '%s'",
                $this->container['objeto_imp'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clave_prod_serv
     *
     * @return string
     */
    public function getClaveProdServ()
    {
        return $this->container['clave_prod_serv'];
    }

    /**
     * Sets clave_prod_serv
     *
     * @param string $clave_prod_serv clave_prod_serv
     *
     * @return self
     */
    public function setClaveProdServ($clave_prod_serv)
    {
        if (is_null($clave_prod_serv)) {
            throw new \InvalidArgumentException('non-nullable clave_prod_serv cannot be null');
        }
        $this->container['clave_prod_serv'] = $clave_prod_serv;

        return $this;
    }

    /**
     * Gets no_identificacion
     *
     * @return string|null
     */
    public function getNoIdentificacion()
    {
        return $this->container['no_identificacion'];
    }

    /**
     * Sets no_identificacion
     *
     * @param string|null $no_identificacion no_identificacion
     *
     * @return self
     */
    public function setNoIdentificacion($no_identificacion)
    {
        if (is_null($no_identificacion)) {
            array_push($this->openAPINullablesSetToNull, 'no_identificacion');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('no_identificacion', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['no_identificacion'] = $no_identificacion;

        return $this;
    }

    /**
     * Gets cantidad
     *
     * @return string
     */
    public function getCantidad()
    {
        return $this->container['cantidad'];
    }

    /**
     * Sets cantidad
     *
     * @param string $cantidad cantidad
     *
     * @return self
     */
    public function setCantidad($cantidad)
    {
        if (is_null($cantidad)) {
            throw new \InvalidArgumentException('non-nullable cantidad cannot be null');
        }
        $this->container['cantidad'] = $cantidad;

        return $this;
    }

    /**
     * Gets clave_unidad
     *
     * @return string
     */
    public function getClaveUnidad()
    {
        return $this->container['clave_unidad'];
    }

    /**
     * Sets clave_unidad
     *
     * @param string $clave_unidad clave_unidad
     *
     * @return self
     */
    public function setClaveUnidad($clave_unidad)
    {
        if (is_null($clave_unidad)) {
            throw new \InvalidArgumentException('non-nullable clave_unidad cannot be null');
        }
        $this->container['clave_unidad'] = $clave_unidad;

        return $this;
    }

    /**
     * Gets unidad
     *
     * @return string|null
     */
    public function getUnidad()
    {
        return $this->container['unidad'];
    }

    /**
     * Sets unidad
     *
     * @param string|null $unidad unidad
     *
     * @return self
     */
    public function setUnidad($unidad)
    {
        if (is_null($unidad)) {
            array_push($this->openAPINullablesSetToNull, 'unidad');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('unidad', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['unidad'] = $unidad;

        return $this;
    }

    /**
     * Gets descripcion
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->container['descripcion'];
    }

    /**
     * Sets descripcion
     *
     * @param string $descripcion descripcion
     *
     * @return self
     */
    public function setDescripcion($descripcion)
    {
        if (is_null($descripcion)) {
            throw new \InvalidArgumentException('non-nullable descripcion cannot be null');
        }
        $this->container['descripcion'] = $descripcion;

        return $this;
    }

    /**
     * Gets valor_unitario
     *
     * @return string
     */
    public function getValorUnitario()
    {
        return $this->container['valor_unitario'];
    }

    /**
     * Sets valor_unitario
     *
     * @param string $valor_unitario valor_unitario
     *
     * @return self
     */
    public function setValorUnitario($valor_unitario)
    {
        if (is_null($valor_unitario)) {
            throw new \InvalidArgumentException('non-nullable valor_unitario cannot be null');
        }
        $this->container['valor_unitario'] = $valor_unitario;

        return $this;
    }

    /**
     * Gets importe
     *
     * @return string
     */
    public function getImporte()
    {
        return $this->container['importe'];
    }

    /**
     * Sets importe
     *
     * @param string $importe importe
     *
     * @return self
     */
    public function setImporte($importe)
    {
        if (is_null($importe)) {
            throw new \InvalidArgumentException('non-nullable importe cannot be null');
        }
        $this->container['importe'] = $importe;

        return $this;
    }

    /**
     * Gets descuento
     *
     * @return string|null
     */
    public function getDescuento()
    {
        return $this->container['descuento'];
    }

    /**
     * Sets descuento
     *
     * @param string|null $descuento descuento
     *
     * @return self
     */
    public function setDescuento($descuento)
    {
        if (is_null($descuento)) {
            array_push($this->openAPINullablesSetToNull, 'descuento');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('descuento', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['descuento'] = $descuento;

        return $this;
    }

    /**
     * Gets objeto_imp
     *
     * @return string
     */
    public function getObjetoImp()
    {
        return $this->container['objeto_imp'];
    }

    /**
     * Sets objeto_imp
     *
     * @param string $objeto_imp 02 = objeto de impuesto.
     *
     * @return self
     */
    public function setObjetoImp($objeto_imp)
    {
        if (is_null($objeto_imp)) {
            throw new \InvalidArgumentException('non-nullable objeto_imp cannot be null');
        }
        $allowedValues = $this->getObjetoImpAllowableValues();
        if (!in_array($objeto_imp, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'objeto_imp', must be one of '%s'",
                    $objeto_imp,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['objeto_imp'] = $objeto_imp;

        return $this;
    }

    /**
     * Gets impuestos
     *
     * @return \Facter\Sdk\Model\ImpuestosConcepto|null
     */
    public function getImpuestos()
    {
        return $this->container['impuestos'];
    }

    /**
     * Sets impuestos
     *
     * @param \Facter\Sdk\Model\ImpuestosConcepto|null $impuestos impuestos
     *
     * @return self
     */
    public function setImpuestos($impuestos)
    {
        if (is_null($impuestos)) {
            throw new \InvalidArgumentException('non-nullable impuestos cannot be null');
        }
        $this->container['impuestos'] = $impuestos;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


