<?php
/**
 * Emisor
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Facter\Sdk\Model;

use \ArrayAccess;
use \Facter\Sdk\ObjectSerializer;

/**
 * Emisor Class Doc Comment
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Emisor implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Emisor';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rfc' => 'string',
        'external_ref' => 'string',
        'razon_social' => 'string',
        'regimen_fiscal' => 'string',
        'codigo_postal' => 'string',
        'is_principal' => 'bool',
        'status' => 'string',
        'reused' => 'bool',
        'csd' => '\Facter\Sdk\Model\EmisorCsd'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rfc' => null,
        'external_ref' => null,
        'razon_social' => null,
        'regimen_fiscal' => null,
        'codigo_postal' => null,
        'is_principal' => null,
        'status' => null,
        'reused' => null,
        'csd' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rfc' => false,
        'external_ref' => true,
        'razon_social' => false,
        'regimen_fiscal' => false,
        'codigo_postal' => false,
        'is_principal' => false,
        'status' => false,
        'reused' => false,
        'csd' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rfc' => 'rfc',
        'external_ref' => 'external_ref',
        'razon_social' => 'razon_social',
        'regimen_fiscal' => 'regimen_fiscal',
        'codigo_postal' => 'codigo_postal',
        'is_principal' => 'is_principal',
        'status' => 'status',
        'reused' => 'reused',
        'csd' => 'csd'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rfc' => 'setRfc',
        'external_ref' => 'setExternalRef',
        'razon_social' => 'setRazonSocial',
        'regimen_fiscal' => 'setRegimenFiscal',
        'codigo_postal' => 'setCodigoPostal',
        'is_principal' => 'setIsPrincipal',
        'status' => 'setStatus',
        'reused' => 'setReused',
        'csd' => 'setCsd'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rfc' => 'getRfc',
        'external_ref' => 'getExternalRef',
        'razon_social' => 'getRazonSocial',
        'regimen_fiscal' => 'getRegimenFiscal',
        'codigo_postal' => 'getCodigoPostal',
        'is_principal' => 'getIsPrincipal',
        'status' => 'getStatus',
        'reused' => 'getReused',
        'csd' => 'getCsd'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_ACTIVO = 'ACTIVO';
    public const STATUS_SUSPENDIDO = 'SUSPENDIDO';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_ACTIVO,
            self::STATUS_SUSPENDIDO,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rfc', $data ?? [], null);
        $this->setIfExists('external_ref', $data ?? [], null);
        $this->setIfExists('razon_social', $data ?? [], null);
        $this->setIfExists('regimen_fiscal', $data ?? [], null);
        $this->setIfExists('codigo_postal', $data ?? [], null);
        $this->setIfExists('is_principal', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('reused', $data ?? [], null);
        $this->setIfExists('csd', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rfc
     *
     * @return string|null
     */
    public function getRfc()
    {
        return $this->container['rfc'];
    }

    /**
     * Sets rfc
     *
     * @param string|null $rfc rfc
     *
     * @return self
     */
    public function setRfc($rfc)
    {
        if (is_null($rfc)) {
            throw new \InvalidArgumentException('non-nullable rfc cannot be null');
        }
        $this->container['rfc'] = $rfc;

        return $this;
    }

    /**
     * Gets external_ref
     *
     * @return string|null
     */
    public function getExternalRef()
    {
        return $this->container['external_ref'];
    }

    /**
     * Sets external_ref
     *
     * @param string|null $external_ref external_ref
     *
     * @return self
     */
    public function setExternalRef($external_ref)
    {
        if (is_null($external_ref)) {
            array_push($this->openAPINullablesSetToNull, 'external_ref');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_ref', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_ref'] = $external_ref;

        return $this;
    }

    /**
     * Gets razon_social
     *
     * @return string|null
     */
    public function getRazonSocial()
    {
        return $this->container['razon_social'];
    }

    /**
     * Sets razon_social
     *
     * @param string|null $razon_social razon_social
     *
     * @return self
     */
    public function setRazonSocial($razon_social)
    {
        if (is_null($razon_social)) {
            throw new \InvalidArgumentException('non-nullable razon_social cannot be null');
        }
        $this->container['razon_social'] = $razon_social;

        return $this;
    }

    /**
     * Gets regimen_fiscal
     *
     * @return string|null
     */
    public function getRegimenFiscal()
    {
        return $this->container['regimen_fiscal'];
    }

    /**
     * Sets regimen_fiscal
     *
     * @param string|null $regimen_fiscal regimen_fiscal
     *
     * @return self
     */
    public function setRegimenFiscal($regimen_fiscal)
    {
        if (is_null($regimen_fiscal)) {
            throw new \InvalidArgumentException('non-nullable regimen_fiscal cannot be null');
        }
        $this->container['regimen_fiscal'] = $regimen_fiscal;

        return $this;
    }

    /**
     * Gets codigo_postal
     *
     * @return string|null
     */
    public function getCodigoPostal()
    {
        return $this->container['codigo_postal'];
    }

    /**
     * Sets codigo_postal
     *
     * @param string|null $codigo_postal codigo_postal
     *
     * @return self
     */
    public function setCodigoPostal($codigo_postal)
    {
        if (is_null($codigo_postal)) {
            throw new \InvalidArgumentException('non-nullable codigo_postal cannot be null');
        }
        $this->container['codigo_postal'] = $codigo_postal;

        return $this;
    }

    /**
     * Gets is_principal
     *
     * @return bool|null
     */
    public function getIsPrincipal()
    {
        return $this->container['is_principal'];
    }

    /**
     * Sets is_principal
     *
     * @param bool|null $is_principal true si el emisor es tu propia cuenta principal (registrada automáticamente al activar el API). Consume su propio saldo PREPAGO —la misma bolsa que financia el pool— y no puede desvincularse.
     *
     * @return self
     */
    public function setIsPrincipal($is_principal)
    {
        if (is_null($is_principal)) {
            throw new \InvalidArgumentException('non-nullable is_principal cannot be null');
        }
        $this->container['is_principal'] = $is_principal;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets reused
     *
     * @return bool|null
     */
    public function getReused()
    {
        return $this->container['reused'];
    }

    /**
     * Sets reused
     *
     * @param bool|null $reused true si se vinculó una cuenta existente con el mismo RFC (respuesta 200); false si se creó un tenant nuevo (respuesta 201).
     *
     * @return self
     */
    public function setReused($reused)
    {
        if (is_null($reused)) {
            throw new \InvalidArgumentException('non-nullable reused cannot be null');
        }
        $this->container['reused'] = $reused;

        return $this;
    }

    /**
     * Gets csd
     *
     * @return \Facter\Sdk\Model\EmisorCsd|null
     */
    public function getCsd()
    {
        return $this->container['csd'];
    }

    /**
     * Sets csd
     *
     * @param \Facter\Sdk\Model\EmisorCsd|null $csd csd
     *
     * @return self
     */
    public function setCsd($csd)
    {
        if (is_null($csd)) {
            array_push($this->openAPINullablesSetToNull, 'csd');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('csd', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['csd'] = $csd;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


