<?php
/**
 * Pago20
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Facter\Sdk\Model;

use \ArrayAccess;
use \Facter\Sdk\ObjectSerializer;

/**
 * Pago20 Class Doc Comment
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Pago20 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Pago20';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fecha_pago' => 'string',
        'forma_de_pago_p' => 'string',
        'moneda_p' => 'string',
        'tipo_cambio_p' => 'string',
        'monto' => 'string',
        'doctos_relacionados' => '\Facter\Sdk\Model\Pago20DoctosRelacionadosInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fecha_pago' => null,
        'forma_de_pago_p' => null,
        'moneda_p' => null,
        'tipo_cambio_p' => null,
        'monto' => null,
        'doctos_relacionados' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fecha_pago' => false,
        'forma_de_pago_p' => false,
        'moneda_p' => false,
        'tipo_cambio_p' => true,
        'monto' => false,
        'doctos_relacionados' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fecha_pago' => 'FechaPago',
        'forma_de_pago_p' => 'FormaDePagoP',
        'moneda_p' => 'MonedaP',
        'tipo_cambio_p' => 'TipoCambioP',
        'monto' => 'Monto',
        'doctos_relacionados' => 'DoctosRelacionados'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fecha_pago' => 'setFechaPago',
        'forma_de_pago_p' => 'setFormaDePagoP',
        'moneda_p' => 'setMonedaP',
        'tipo_cambio_p' => 'setTipoCambioP',
        'monto' => 'setMonto',
        'doctos_relacionados' => 'setDoctosRelacionados'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fecha_pago' => 'getFechaPago',
        'forma_de_pago_p' => 'getFormaDePagoP',
        'moneda_p' => 'getMonedaP',
        'tipo_cambio_p' => 'getTipoCambioP',
        'monto' => 'getMonto',
        'doctos_relacionados' => 'getDoctosRelacionados'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fecha_pago', $data ?? [], null);
        $this->setIfExists('forma_de_pago_p', $data ?? [], null);
        $this->setIfExists('moneda_p', $data ?? [], null);
        $this->setIfExists('tipo_cambio_p', $data ?? [], null);
        $this->setIfExists('monto', $data ?? [], null);
        $this->setIfExists('doctos_relacionados', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['fecha_pago'] === null) {
            $invalidProperties[] = "'fecha_pago' can't be null";
        }
        if ($this->container['forma_de_pago_p'] === null) {
            $invalidProperties[] = "'forma_de_pago_p' can't be null";
        }
        if ($this->container['moneda_p'] === null) {
            $invalidProperties[] = "'moneda_p' can't be null";
        }
        if ($this->container['monto'] === null) {
            $invalidProperties[] = "'monto' can't be null";
        }
        if ($this->container['doctos_relacionados'] === null) {
            $invalidProperties[] = "'doctos_relacionados' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fecha_pago
     *
     * @return string
     */
    public function getFechaPago()
    {
        return $this->container['fecha_pago'];
    }

    /**
     * Sets fecha_pago
     *
     * @param string $fecha_pago fecha_pago
     *
     * @return self
     */
    public function setFechaPago($fecha_pago)
    {
        if (is_null($fecha_pago)) {
            throw new \InvalidArgumentException('non-nullable fecha_pago cannot be null');
        }
        $this->container['fecha_pago'] = $fecha_pago;

        return $this;
    }

    /**
     * Gets forma_de_pago_p
     *
     * @return string
     */
    public function getFormaDePagoP()
    {
        return $this->container['forma_de_pago_p'];
    }

    /**
     * Sets forma_de_pago_p
     *
     * @param string $forma_de_pago_p forma_de_pago_p
     *
     * @return self
     */
    public function setFormaDePagoP($forma_de_pago_p)
    {
        if (is_null($forma_de_pago_p)) {
            throw new \InvalidArgumentException('non-nullable forma_de_pago_p cannot be null');
        }
        $this->container['forma_de_pago_p'] = $forma_de_pago_p;

        return $this;
    }

    /**
     * Gets moneda_p
     *
     * @return string
     */
    public function getMonedaP()
    {
        return $this->container['moneda_p'];
    }

    /**
     * Sets moneda_p
     *
     * @param string $moneda_p moneda_p
     *
     * @return self
     */
    public function setMonedaP($moneda_p)
    {
        if (is_null($moneda_p)) {
            throw new \InvalidArgumentException('non-nullable moneda_p cannot be null');
        }
        $this->container['moneda_p'] = $moneda_p;

        return $this;
    }

    /**
     * Gets tipo_cambio_p
     *
     * @return string|null
     */
    public function getTipoCambioP()
    {
        return $this->container['tipo_cambio_p'];
    }

    /**
     * Sets tipo_cambio_p
     *
     * @param string|null $tipo_cambio_p tipo_cambio_p
     *
     * @return self
     */
    public function setTipoCambioP($tipo_cambio_p)
    {
        if (is_null($tipo_cambio_p)) {
            array_push($this->openAPINullablesSetToNull, 'tipo_cambio_p');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tipo_cambio_p', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tipo_cambio_p'] = $tipo_cambio_p;

        return $this;
    }

    /**
     * Gets monto
     *
     * @return string
     */
    public function getMonto()
    {
        return $this->container['monto'];
    }

    /**
     * Sets monto
     *
     * @param string $monto monto
     *
     * @return self
     */
    public function setMonto($monto)
    {
        if (is_null($monto)) {
            throw new \InvalidArgumentException('non-nullable monto cannot be null');
        }
        $this->container['monto'] = $monto;

        return $this;
    }

    /**
     * Gets doctos_relacionados
     *
     * @return \Facter\Sdk\Model\Pago20DoctosRelacionadosInner[]
     */
    public function getDoctosRelacionados()
    {
        return $this->container['doctos_relacionados'];
    }

    /**
     * Sets doctos_relacionados
     *
     * @param \Facter\Sdk\Model\Pago20DoctosRelacionadosInner[] $doctos_relacionados doctos_relacionados
     *
     * @return self
     */
    public function setDoctosRelacionados($doctos_relacionados)
    {
        if (is_null($doctos_relacionados)) {
            throw new \InvalidArgumentException('non-nullable doctos_relacionados cannot be null');
        }
        $this->container['doctos_relacionados'] = $doctos_relacionados;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


