<?php
/**
 * Pago20DoctosRelacionadosInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Facter\Sdk\Model;

use \ArrayAccess;
use \Facter\Sdk\ObjectSerializer;

/**
 * Pago20DoctosRelacionadosInner Class Doc Comment
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Pago20DoctosRelacionadosInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Pago20_DoctosRelacionados_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id_documento' => 'string',
        'serie' => 'string',
        'folio' => 'string',
        'moneda_dr' => 'string',
        'equivalencia_dr' => 'string',
        'num_parcialidad' => 'string',
        'imp_saldo_ant' => 'string',
        'imp_pagado' => 'string',
        'imp_saldo_insoluto' => 'string',
        'objeto_imp_dr' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id_documento' => 'uuid',
        'serie' => null,
        'folio' => null,
        'moneda_dr' => null,
        'equivalencia_dr' => null,
        'num_parcialidad' => null,
        'imp_saldo_ant' => null,
        'imp_pagado' => null,
        'imp_saldo_insoluto' => null,
        'objeto_imp_dr' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id_documento' => false,
        'serie' => true,
        'folio' => true,
        'moneda_dr' => false,
        'equivalencia_dr' => true,
        'num_parcialidad' => false,
        'imp_saldo_ant' => false,
        'imp_pagado' => false,
        'imp_saldo_insoluto' => false,
        'objeto_imp_dr' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_documento' => 'IdDocumento',
        'serie' => 'Serie',
        'folio' => 'Folio',
        'moneda_dr' => 'MonedaDR',
        'equivalencia_dr' => 'EquivalenciaDR',
        'num_parcialidad' => 'NumParcialidad',
        'imp_saldo_ant' => 'ImpSaldoAnt',
        'imp_pagado' => 'ImpPagado',
        'imp_saldo_insoluto' => 'ImpSaldoInsoluto',
        'objeto_imp_dr' => 'ObjetoImpDR'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_documento' => 'setIdDocumento',
        'serie' => 'setSerie',
        'folio' => 'setFolio',
        'moneda_dr' => 'setMonedaDr',
        'equivalencia_dr' => 'setEquivalenciaDr',
        'num_parcialidad' => 'setNumParcialidad',
        'imp_saldo_ant' => 'setImpSaldoAnt',
        'imp_pagado' => 'setImpPagado',
        'imp_saldo_insoluto' => 'setImpSaldoInsoluto',
        'objeto_imp_dr' => 'setObjetoImpDr'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_documento' => 'getIdDocumento',
        'serie' => 'getSerie',
        'folio' => 'getFolio',
        'moneda_dr' => 'getMonedaDr',
        'equivalencia_dr' => 'getEquivalenciaDr',
        'num_parcialidad' => 'getNumParcialidad',
        'imp_saldo_ant' => 'getImpSaldoAnt',
        'imp_pagado' => 'getImpPagado',
        'imp_saldo_insoluto' => 'getImpSaldoInsoluto',
        'objeto_imp_dr' => 'getObjetoImpDr'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id_documento', $data ?? [], null);
        $this->setIfExists('serie', $data ?? [], null);
        $this->setIfExists('folio', $data ?? [], null);
        $this->setIfExists('moneda_dr', $data ?? [], null);
        $this->setIfExists('equivalencia_dr', $data ?? [], null);
        $this->setIfExists('num_parcialidad', $data ?? [], null);
        $this->setIfExists('imp_saldo_ant', $data ?? [], null);
        $this->setIfExists('imp_pagado', $data ?? [], null);
        $this->setIfExists('imp_saldo_insoluto', $data ?? [], null);
        $this->setIfExists('objeto_imp_dr', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_documento
     *
     * @return string|null
     */
    public function getIdDocumento()
    {
        return $this->container['id_documento'];
    }

    /**
     * Sets id_documento
     *
     * @param string|null $id_documento UUID del CFDI de ingreso pagado.
     *
     * @return self
     */
    public function setIdDocumento($id_documento)
    {
        if (is_null($id_documento)) {
            throw new \InvalidArgumentException('non-nullable id_documento cannot be null');
        }
        $this->container['id_documento'] = $id_documento;

        return $this;
    }

    /**
     * Gets serie
     *
     * @return string|null
     */
    public function getSerie()
    {
        return $this->container['serie'];
    }

    /**
     * Sets serie
     *
     * @param string|null $serie serie
     *
     * @return self
     */
    public function setSerie($serie)
    {
        if (is_null($serie)) {
            array_push($this->openAPINullablesSetToNull, 'serie');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('serie', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['serie'] = $serie;

        return $this;
    }

    /**
     * Gets folio
     *
     * @return string|null
     */
    public function getFolio()
    {
        return $this->container['folio'];
    }

    /**
     * Sets folio
     *
     * @param string|null $folio folio
     *
     * @return self
     */
    public function setFolio($folio)
    {
        if (is_null($folio)) {
            array_push($this->openAPINullablesSetToNull, 'folio');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('folio', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['folio'] = $folio;

        return $this;
    }

    /**
     * Gets moneda_dr
     *
     * @return string|null
     */
    public function getMonedaDr()
    {
        return $this->container['moneda_dr'];
    }

    /**
     * Sets moneda_dr
     *
     * @param string|null $moneda_dr moneda_dr
     *
     * @return self
     */
    public function setMonedaDr($moneda_dr)
    {
        if (is_null($moneda_dr)) {
            throw new \InvalidArgumentException('non-nullable moneda_dr cannot be null');
        }
        $this->container['moneda_dr'] = $moneda_dr;

        return $this;
    }

    /**
     * Gets equivalencia_dr
     *
     * @return string|null
     */
    public function getEquivalenciaDr()
    {
        return $this->container['equivalencia_dr'];
    }

    /**
     * Sets equivalencia_dr
     *
     * @param string|null $equivalencia_dr Tipo de cambio del documento a la moneda del pago. Obligatorio y = \"1\" cuando MonedaDR = MonedaP (regla SAT CRP20238).
     *
     * @return self
     */
    public function setEquivalenciaDr($equivalencia_dr)
    {
        if (is_null($equivalencia_dr)) {
            array_push($this->openAPINullablesSetToNull, 'equivalencia_dr');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('equivalencia_dr', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['equivalencia_dr'] = $equivalencia_dr;

        return $this;
    }

    /**
     * Gets num_parcialidad
     *
     * @return string|null
     */
    public function getNumParcialidad()
    {
        return $this->container['num_parcialidad'];
    }

    /**
     * Sets num_parcialidad
     *
     * @param string|null $num_parcialidad num_parcialidad
     *
     * @return self
     */
    public function setNumParcialidad($num_parcialidad)
    {
        if (is_null($num_parcialidad)) {
            throw new \InvalidArgumentException('non-nullable num_parcialidad cannot be null');
        }
        $this->container['num_parcialidad'] = $num_parcialidad;

        return $this;
    }

    /**
     * Gets imp_saldo_ant
     *
     * @return string|null
     */
    public function getImpSaldoAnt()
    {
        return $this->container['imp_saldo_ant'];
    }

    /**
     * Sets imp_saldo_ant
     *
     * @param string|null $imp_saldo_ant imp_saldo_ant
     *
     * @return self
     */
    public function setImpSaldoAnt($imp_saldo_ant)
    {
        if (is_null($imp_saldo_ant)) {
            throw new \InvalidArgumentException('non-nullable imp_saldo_ant cannot be null');
        }
        $this->container['imp_saldo_ant'] = $imp_saldo_ant;

        return $this;
    }

    /**
     * Gets imp_pagado
     *
     * @return string|null
     */
    public function getImpPagado()
    {
        return $this->container['imp_pagado'];
    }

    /**
     * Sets imp_pagado
     *
     * @param string|null $imp_pagado imp_pagado
     *
     * @return self
     */
    public function setImpPagado($imp_pagado)
    {
        if (is_null($imp_pagado)) {
            throw new \InvalidArgumentException('non-nullable imp_pagado cannot be null');
        }
        $this->container['imp_pagado'] = $imp_pagado;

        return $this;
    }

    /**
     * Gets imp_saldo_insoluto
     *
     * @return string|null
     */
    public function getImpSaldoInsoluto()
    {
        return $this->container['imp_saldo_insoluto'];
    }

    /**
     * Sets imp_saldo_insoluto
     *
     * @param string|null $imp_saldo_insoluto imp_saldo_insoluto
     *
     * @return self
     */
    public function setImpSaldoInsoluto($imp_saldo_insoluto)
    {
        if (is_null($imp_saldo_insoluto)) {
            throw new \InvalidArgumentException('non-nullable imp_saldo_insoluto cannot be null');
        }
        $this->container['imp_saldo_insoluto'] = $imp_saldo_insoluto;

        return $this;
    }

    /**
     * Gets objeto_imp_dr
     *
     * @return string|null
     */
    public function getObjetoImpDr()
    {
        return $this->container['objeto_imp_dr'];
    }

    /**
     * Sets objeto_imp_dr
     *
     * @param string|null $objeto_imp_dr objeto_imp_dr
     *
     * @return self
     */
    public function setObjetoImpDr($objeto_imp_dr)
    {
        if (is_null($objeto_imp_dr)) {
            throw new \InvalidArgumentException('non-nullable objeto_imp_dr cannot be null');
        }
        $this->container['objeto_imp_dr'] = $objeto_imp_dr;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


