<?php
/**
 * Retencion
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Facter\Sdk\Model;

use \ArrayAccess;
use \Facter\Sdk\ObjectSerializer;

/**
 * Retencion Class Doc Comment
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Retencion implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Retencion';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'base' => 'string',
        'impuesto' => 'string',
        'tipo_factor' => 'string',
        'tasa_o_cuota' => 'string',
        'importe' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'base' => null,
        'impuesto' => null,
        'tipo_factor' => null,
        'tasa_o_cuota' => null,
        'importe' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'base' => false,
        'impuesto' => false,
        'tipo_factor' => false,
        'tasa_o_cuota' => false,
        'importe' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'base' => 'Base',
        'impuesto' => 'Impuesto',
        'tipo_factor' => 'TipoFactor',
        'tasa_o_cuota' => 'TasaOCuota',
        'importe' => 'Importe'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'base' => 'setBase',
        'impuesto' => 'setImpuesto',
        'tipo_factor' => 'setTipoFactor',
        'tasa_o_cuota' => 'setTasaOCuota',
        'importe' => 'setImporte'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'base' => 'getBase',
        'impuesto' => 'getImpuesto',
        'tipo_factor' => 'getTipoFactor',
        'tasa_o_cuota' => 'getTasaOCuota',
        'importe' => 'getImporte'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TIPO_FACTOR_TASA = 'Tasa';
    public const TIPO_FACTOR_CUOTA = 'Cuota';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTipoFactorAllowableValues()
    {
        return [
            self::TIPO_FACTOR_TASA,
            self::TIPO_FACTOR_CUOTA,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('base', $data ?? [], null);
        $this->setIfExists('impuesto', $data ?? [], null);
        $this->setIfExists('tipo_factor', $data ?? [], null);
        $this->setIfExists('tasa_o_cuota', $data ?? [], null);
        $this->setIfExists('importe', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['base'] === null) {
            $invalidProperties[] = "'base' can't be null";
        }
        if ($this->container['impuesto'] === null) {
            $invalidProperties[] = "'impuesto' can't be null";
        }
        if ($this->container['tipo_factor'] === null) {
            $invalidProperties[] = "'tipo_factor' can't be null";
        }
        $allowedValues = $this->getTipoFactorAllowableValues();
        if (!is_null($this->container['tipo_factor']) && !in_array($this->container['tipo_factor'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tipo_factor', must be one of '%s'",
                $this->container['tipo_factor'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['tasa_o_cuota'] === null) {
            $invalidProperties[] = "'tasa_o_cuota' can't be null";
        }
        if ($this->container['importe'] === null) {
            $invalidProperties[] = "'importe' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets base
     *
     * @return string
     */
    public function getBase()
    {
        return $this->container['base'];
    }

    /**
     * Sets base
     *
     * @param string $base base
     *
     * @return self
     */
    public function setBase($base)
    {
        if (is_null($base)) {
            throw new \InvalidArgumentException('non-nullable base cannot be null');
        }
        $this->container['base'] = $base;

        return $this;
    }

    /**
     * Gets impuesto
     *
     * @return string
     */
    public function getImpuesto()
    {
        return $this->container['impuesto'];
    }

    /**
     * Sets impuesto
     *
     * @param string $impuesto impuesto
     *
     * @return self
     */
    public function setImpuesto($impuesto)
    {
        if (is_null($impuesto)) {
            throw new \InvalidArgumentException('non-nullable impuesto cannot be null');
        }
        $this->container['impuesto'] = $impuesto;

        return $this;
    }

    /**
     * Gets tipo_factor
     *
     * @return string
     */
    public function getTipoFactor()
    {
        return $this->container['tipo_factor'];
    }

    /**
     * Sets tipo_factor
     *
     * @param string $tipo_factor tipo_factor
     *
     * @return self
     */
    public function setTipoFactor($tipo_factor)
    {
        if (is_null($tipo_factor)) {
            throw new \InvalidArgumentException('non-nullable tipo_factor cannot be null');
        }
        $allowedValues = $this->getTipoFactorAllowableValues();
        if (!in_array($tipo_factor, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tipo_factor', must be one of '%s'",
                    $tipo_factor,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tipo_factor'] = $tipo_factor;

        return $this;
    }

    /**
     * Gets tasa_o_cuota
     *
     * @return string
     */
    public function getTasaOCuota()
    {
        return $this->container['tasa_o_cuota'];
    }

    /**
     * Sets tasa_o_cuota
     *
     * @param string $tasa_o_cuota tasa_o_cuota
     *
     * @return self
     */
    public function setTasaOCuota($tasa_o_cuota)
    {
        if (is_null($tasa_o_cuota)) {
            throw new \InvalidArgumentException('non-nullable tasa_o_cuota cannot be null');
        }
        $this->container['tasa_o_cuota'] = $tasa_o_cuota;

        return $this;
    }

    /**
     * Gets importe
     *
     * @return string
     */
    public function getImporte()
    {
        return $this->container['importe'];
    }

    /**
     * Sets importe
     *
     * @param string $importe importe
     *
     * @return self
     */
    public function setImporte($importe)
    {
        if (is_null($importe)) {
            throw new \InvalidArgumentException('non-nullable importe cannot be null');
        }
        $this->container['importe'] = $importe;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


