<?php
/**
 * StampRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Facter\Sdk\Model;

use \ArrayAccess;
use \Facter\Sdk\ObjectSerializer;

/**
 * StampRequest Class Doc Comment
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StampRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StampRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'emisor_rfc' => 'string',
        'external_ref' => 'string',
        'fecha_emision' => 'string',
        'cfdi' => '\Facter\Sdk\Model\Comprobante'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'emisor_rfc' => null,
        'external_ref' => null,
        'fecha_emision' => null,
        'cfdi' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'emisor_rfc' => false,
        'external_ref' => true,
        'fecha_emision' => true,
        'cfdi' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'emisor_rfc' => 'emisor_rfc',
        'external_ref' => 'external_ref',
        'fecha_emision' => 'fecha_emision',
        'cfdi' => 'cfdi'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'emisor_rfc' => 'setEmisorRfc',
        'external_ref' => 'setExternalRef',
        'fecha_emision' => 'setFechaEmision',
        'cfdi' => 'setCfdi'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'emisor_rfc' => 'getEmisorRfc',
        'external_ref' => 'getExternalRef',
        'fecha_emision' => 'getFechaEmision',
        'cfdi' => 'getCfdi'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('emisor_rfc', $data ?? [], null);
        $this->setIfExists('external_ref', $data ?? [], null);
        $this->setIfExists('fecha_emision', $data ?? [], null);
        $this->setIfExists('cfdi', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['emisor_rfc'] === null) {
            $invalidProperties[] = "'emisor_rfc' can't be null";
        }
        if ($this->container['cfdi'] === null) {
            $invalidProperties[] = "'cfdi' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets emisor_rfc
     *
     * @return string
     */
    public function getEmisorRfc()
    {
        return $this->container['emisor_rfc'];
    }

    /**
     * Sets emisor_rfc
     *
     * @param string $emisor_rfc RFC de un emisor ACTIVO del cliente con CSD vigente. Debe coincidir con cfdi.Emisor.Rfc. Puede ser el RFC de tu propia cuenta principal (timbra contra su propio saldo PREPAGO).
     *
     * @return self
     */
    public function setEmisorRfc($emisor_rfc)
    {
        if (is_null($emisor_rfc)) {
            throw new \InvalidArgumentException('non-nullable emisor_rfc cannot be null');
        }
        $this->container['emisor_rfc'] = $emisor_rfc;

        return $this;
    }

    /**
     * Gets external_ref
     *
     * @return string|null
     */
    public function getExternalRef()
    {
        return $this->container['external_ref'];
    }

    /**
     * Sets external_ref
     *
     * @param string|null $external_ref Referencia del integrador; se devuelve en consultas y webhooks.
     *
     * @return self
     */
    public function setExternalRef($external_ref)
    {
        if (is_null($external_ref)) {
            array_push($this->openAPINullablesSetToNull, 'external_ref');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_ref', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_ref'] = $external_ref;

        return $this;
    }

    /**
     * Gets fecha_emision
     *
     * @return string|null
     */
    public function getFechaEmision()
    {
        return $this->container['fecha_emision'];
    }

    /**
     * Sets fecha_emision
     *
     * @param string|null $fecha_emision Opcional. Si se envía: ventana máx. 72 h hacia atrás, nunca futura (zona horaria por CP). Si es null, la fija Facter al timbrar.
     *
     * @return self
     */
    public function setFechaEmision($fecha_emision)
    {
        if (is_null($fecha_emision)) {
            array_push($this->openAPINullablesSetToNull, 'fecha_emision');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fecha_emision', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fecha_emision'] = $fecha_emision;

        return $this;
    }

    /**
     * Gets cfdi
     *
     * @return \Facter\Sdk\Model\Comprobante
     */
    public function getCfdi()
    {
        return $this->container['cfdi'];
    }

    /**
     * Sets cfdi
     *
     * @param \Facter\Sdk\Model\Comprobante $cfdi cfdi
     *
     * @return self
     */
    public function setCfdi($cfdi)
    {
        if (is_null($cfdi)) {
            throw new \InvalidArgumentException('non-nullable cfdi cannot be null');
        }
        $this->container['cfdi'] = $cfdi;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


