<?php
/**
 * ComprobanteTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Facter\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ComprobanteTest Class Doc Comment
 *
 * @category    Class
 * @description Comprobante CFDI 4.0 canónico. Los totales e impuestos los calcula el integrador; Facter valida pero no recalcula. Sello/NoCertificado/Certificado se ignoran si vienen — los pone Facter.
 * @package     Facter\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ComprobanteTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Comprobante"
     */
    public function testComprobante()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serie"
     */
    public function testPropertySerie()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "folio"
     */
    public function testPropertyFolio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "forma_pago"
     */
    public function testPropertyFormaPago()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "metodo_pago"
     */
    public function testPropertyMetodoPago()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "condiciones_de_pago"
     */
    public function testPropertyCondicionesDePago()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sub_total"
     */
    public function testPropertySubTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descuento"
     */
    public function testPropertyDescuento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "moneda"
     */
    public function testPropertyMoneda()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_cambio"
     */
    public function testPropertyTipoCambio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_de_comprobante"
     */
    public function testPropertyTipoDeComprobante()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "exportacion"
     */
    public function testPropertyExportacion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lugar_expedicion"
     */
    public function testPropertyLugarExpedicion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emisor"
     */
    public function testPropertyEmisor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "receptor"
     */
    public function testPropertyReceptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "conceptos"
     */
    public function testPropertyConceptos()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "impuestos"
     */
    public function testPropertyImpuestos()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cfdi_relacionados"
     */
    public function testPropertyCfdiRelacionados()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "complemento"
     */
    public function testPropertyComplemento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "informacion_global"
     */
    public function testPropertyInformacionGlobal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
