<?php
/**
 * Pago20DoctosRelacionadosInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Facter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Facter — API de Timbrado para Integradores
 *
 * API pública para timbrar **CFDI 4.0** usando la infraestructura de Facter.  **Modelo comercial:** un **cliente principal** (plan PREPAGO) compra timbres; sus **emisores** (cada uno un tenant con su propio RFC y CSD) consumen del saldo del principal.  El contrato de entrada es el **JSON canónico CFDI 4.0**: el integrador envía el comprobante completo (Emisor, Receptor, Conceptos, Impuestos, Complemento...). Facter **valida** consistencia aritmética y contra catálogos SAT pero **no recalcula** totales — tu sistema es el sistema de registro.  **Ambientes:** prueba en **Demo** `https://demo.facter.com.mx/api/ext/v1` (sandbox de pruebas, sin cobro real, datos efímeros) y, cuando estés listo, pasa a **Producción** `https://v2.facter.com.mx/api/ext/v1` (timbrado real, consume timbres). Necesitas **una cuenta y una API key por ambiente**; la key de un ambiente no funciona en el otro. El host define el comportamiento.  **Autenticación:** `Authorization: Bearer fct_live_xxx`. **Idempotencia obligatoria** en endpoints mutadores vía header `Idempotency-Key`. Toda respuesta incluye `X-Request-Id` para soporte.  Documentación completa, quickstart y ejemplos: https://v2.facter.com.mx/developers
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: soporte@facter.com.mx
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Facter\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * Pago20DoctosRelacionadosInnerTest Class Doc Comment
 *
 * @category    Class
 * @description Pago20DoctosRelacionadosInner
 * @package     Facter\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Pago20DoctosRelacionadosInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Pago20DoctosRelacionadosInner"
     */
    public function testPago20DoctosRelacionadosInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id_documento"
     */
    public function testPropertyIdDocumento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serie"
     */
    public function testPropertySerie()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "folio"
     */
    public function testPropertyFolio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "moneda_dr"
     */
    public function testPropertyMonedaDr()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "equivalencia_dr"
     */
    public function testPropertyEquivalenciaDr()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "num_parcialidad"
     */
    public function testPropertyNumParcialidad()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "imp_saldo_ant"
     */
    public function testPropertyImpSaldoAnt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "imp_pagado"
     */
    public function testPropertyImpPagado()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "imp_saldo_insoluto"
     */
    public function testPropertyImpSaldoInsoluto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objeto_imp_dr"
     */
    public function testPropertyObjetoImpDr()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
